//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YALV.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YALV.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_AboutGroupBox_Header {
            get {
                return ResourceManager.GetString("About_AboutGroupBox_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string About_CreditsGroupBox_Header {
            get {
                return ResourceManager.GetString("About_CreditsGroupBox_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YALV! is a log viewer for Log4Net that allows to compare multiple log files simultaneously.
        ///
        ///MAIN FEATURES:
        ///- Log files merging
        ///- Dynamic filtering
        ///- Dynamic show/hide log levels
        ///- Save favorite log folders
        ///- Open most recently used files
        ///- Column sorting
        ///
        ///Log4Net config file must be setup with XmlLayoutSchemaLog4j layout; just need a few lines in your application config file to configure it to use this format (see examples on right).
        ///
        ///It is a WPF Application based on .NET Framework 4.0 and written with C#  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string About_Description {
            get {
                return ResourceManager.GetString("About_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YALV! - Yet Another Log4Net Viewer.
        /// </summary>
        public static string About_Header_Text {
            get {
                return ResourceManager.GetString("About_Header_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log4Net Configuration.
        /// </summary>
        public static string About_Log4NetConfigurationGroupbox_Header {
            get {
                return ResourceManager.GetString("About_Log4NetConfigurationGroupbox_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample 1:.
        /// </summary>
        public static string About_Log4NetConfigurationGroupbox_Sample1_Title {
            get {
                return ResourceManager.GetString("About_Log4NetConfigurationGroupbox_Sample1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample 2:.
        /// </summary>
        public static string About_Log4NetConfigurationGroupbox_Sample2_Title {
            get {
                return ResourceManager.GetString("About_Log4NetConfigurationGroupbox_Sample2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YALV! - About.
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string About_Version_Text {
            get {
                return ResourceManager.GetString("About_Version_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AddFolderPath_Grid_NameColumn_Name {
            get {
                return ResourceManager.GetString("AddFolderPath_Grid_NameColumn_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string AddFolderPath_Grid_PathColumn_Name {
            get {
                return ResourceManager.GetString("AddFolderPath_Grid_PathColumn_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders list saved!.
        /// </summary>
        public static string AddFolderPathVM_commandSaveExecute_SuccessMessage {
            get {
                return ResourceManager.GetString("AddFolderPathVM_commandSaveExecute_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string AddFolderPathVM_commandSaveExecute_SuccessTitle {
            get {
                return ResourceManager.GetString("AddFolderPathVM_commandSaveExecute_SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string CircularProgressBar_CircularProgressBar_BusyText {
            get {
                return ResourceManager.GetString("CircularProgressBar_CircularProgressBar_BusyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string ColumnSelection_ApplicationInfo_Application {
            get {
                return ResourceManager.GetString("ColumnSelection_ApplicationInfo_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host name.
        /// </summary>
        public static string ColumnSelection_ApplicationInfo_HostName {
            get {
                return ResourceManager.GetString("ColumnSelection_ApplicationInfo_HostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine name.
        /// </summary>
        public static string ColumnSelection_ApplicationInfo_MachineName {
            get {
                return ResourceManager.GetString("ColumnSelection_ApplicationInfo_MachineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string ColumnSelection_ApplicationInfo_UserName {
            get {
                return ResourceManager.GetString("ColumnSelection_ApplicationInfo_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application information.
        /// </summary>
        public static string ColumnSelection_ApplicationInfoGroup_Header {
            get {
                return ResourceManager.GetString("ColumnSelection_ApplicationInfoGroup_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string ColumnSelection_BasicInfo_Level {
            get {
                return ResourceManager.GetString("ColumnSelection_BasicInfo_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logger.
        /// </summary>
        public static string ColumnSelection_BasicInfo_Logger {
            get {
                return ResourceManager.GetString("ColumnSelection_BasicInfo_Logger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string ColumnSelection_BasicInfo_Message {
            get {
                return ResourceManager.GetString("ColumnSelection_BasicInfo_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread.
        /// </summary>
        public static string ColumnSelection_BasicInfo_Thread {
            get {
                return ResourceManager.GetString("ColumnSelection_BasicInfo_Thread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        public static string ColumnSelection_BasicInfo_Timestamp {
            get {
                return ResourceManager.GetString("ColumnSelection_BasicInfo_Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic information.
        /// </summary>
        public static string ColumnSelection_BasicInfoGroup_Header {
            get {
                return ResourceManager.GetString("ColumnSelection_BasicInfoGroup_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ColumnSelection_Button_Cancel {
            get {
                return ResourceManager.GetString("ColumnSelection_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ColumnSelection_Button_OK {
            get {
                return ResourceManager.GetString("ColumnSelection_Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select columns to appear in the Main window:.
        /// </summary>
        public static string ColumnSelection_Description {
            get {
                return ResourceManager.GetString("ColumnSelection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string ColumnSelection_Id {
            get {
                return ResourceManager.GetString("ColumnSelection_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string ColumnSelection_LocationInfo_Class {
            get {
                return ResourceManager.GetString("ColumnSelection_LocationInfo_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        public static string ColumnSelection_LocationInfo_Method {
            get {
                return ResourceManager.GetString("ColumnSelection_LocationInfo_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location information.
        /// </summary>
        public static string ColumnSelection_LocationInfoGroup_Header {
            get {
                return ResourceManager.GetString("ColumnSelection_LocationInfoGroup_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YALV!- Column Selection.
        /// </summary>
        public static string ColumnSelection_Title {
            get {
                return ResourceManager.GetString("ColumnSelection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add folder to Favorites.
        /// </summary>
        public static string Common_Components_AddRemoveMenu_FileMenu_AddNewItem_Header {
            get {
                return ResourceManager.GetString("Common_Components_AddRemoveMenu_FileMenu_AddNewItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Common_Components_AddRemoveMenu_FileMenu_Exit_Header {
            get {
                return ResourceManager.GetString("Common_Components_AddRemoveMenu_FileMenu_Exit_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Common_Components_AddRemoveMenu_FileMenu_Header {
            get {
                return ResourceManager.GetString("Common_Components_AddRemoveMenu_FileMenu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove folder from Favorites.
        /// </summary>
        public static string Common_Components_AddRemoveMenu_FileMenu_RemoveSelectedItem_Header {
            get {
                return ResourceManager.GetString("Common_Components_AddRemoveMenu_FileMenu_RemoveSelectedItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Favorites.
        /// </summary>
        public static string Common_Components_AddRemoveMenu_FileMenu_SaveList_Header {
            get {
                return ResourceManager.GetString("Common_Components_AddRemoveMenu_FileMenu_SaveList_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD.
        /// </summary>
        public static string Common_Components_AddRemoveToolbar_AddNewItem_Text {
            get {
                return ResourceManager.GetString("Common_Components_AddRemoveToolbar_AddNewItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Folder to Favorites.
        /// </summary>
        public static string Common_Components_AddRemoveToolbar_AddNewItem_Tooltip {
            get {
                return ResourceManager.GetString("Common_Components_AddRemoveToolbar_AddNewItem_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REMOVE.
        /// </summary>
        public static string Common_Components_AddRemoveToolbar_RemoveSelectedItem_Text {
            get {
                return ResourceManager.GetString("Common_Components_AddRemoveToolbar_RemoveSelectedItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Selected Folder from Favorites.
        /// </summary>
        public static string Common_Components_AddRemoveToolbar_RemoveSelectedItem_Tooltip {
            get {
                return ResourceManager.GetString("Common_Components_AddRemoveToolbar_RemoveSelectedItem_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        public static string Common_Components_AddRemoveToolbar_SaveList_Text {
            get {
                return ResourceManager.GetString("Common_Components_AddRemoveToolbar_SaveList_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Favorites.
        /// </summary>
        public static string Common_Components_AddRemoveToolbar_SaveList_Tooltip {
            get {
                return ResourceManager.GetString("Common_Components_AddRemoveToolbar_SaveList_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Common_Components_MainMenu_AboutMenu_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_AboutMenu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add File....
        /// </summary>
        public static string Common_Components_MainMenu_FileMenu_AddFile_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_FileMenu_AddFile_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Folder to Favorites....
        /// </summary>
        public static string Common_Components_MainMenu_FileMenu_AddFolderPath_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_FileMenu_AddFolderPath_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Common_Components_MainMenu_FileMenu_Exit_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_FileMenu_Exit_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Common_Components_MainMenu_FileMenu_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_FileMenu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File....
        /// </summary>
        public static string Common_Components_MainMenu_FileMenu_OpenFile_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_FileMenu_OpenFile_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Files.
        /// </summary>
        public static string Common_Components_MainMenu_FileMenu_RecentFiles_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_FileMenu_RecentFiles_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder....
        /// </summary>
        public static string Common_Components_MainMenu_FileMenu_SelectFolder_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_FileMenu_SelectFolder_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Filters.
        /// </summary>
        public static string Common_Components_MainMenu_ViewMenu_ClearFilters_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_ViewMenu_ClearFilters_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete File.
        /// </summary>
        public static string Common_Components_MainMenu_ViewMenu_DeleteFile_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_ViewMenu_DeleteFile_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Common_Components_MainMenu_ViewMenu_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_ViewMenu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open containing Folder in Explorer.
        /// </summary>
        public static string Common_Components_MainMenu_ViewMenu_OpenSelectedFolder_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_ViewMenu_OpenSelectedFolder_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh File List.
        /// </summary>
        public static string Common_Components_MainMenu_ViewMenu_RefreshFileList_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_ViewMenu_RefreshFileList_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Log.
        /// </summary>
        public static string Common_Components_MainMenu_ViewMenu_RefreshLog_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_ViewMenu_RefreshLog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD FILE.
        /// </summary>
        public static string Common_Components_MainToolbar_AddFile_Text {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_AddFile_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add File....
        /// </summary>
        public static string Common_Components_MainToolbar_AddFile_Tooltip {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_AddFile_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD FOLDER.
        /// </summary>
        public static string Common_Components_MainToolbar_AddFolderPath_Text {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_AddFolderPath_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Folder to Favorites....
        /// </summary>
        public static string Common_Components_MainToolbar_AddFolderPath_Tooltip {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_AddFolderPath_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEAR FILTERS.
        /// </summary>
        public static string Common_Components_MainToolbar_ClearFilters_Text {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_ClearFilters_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Filters.
        /// </summary>
        public static string Common_Components_MainToolbar_ClearFilters_Tooltip {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_ClearFilters_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FILE.
        /// </summary>
        public static string Common_Components_MainToolbar_DeleteSelectedFile_Text {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_DeleteSelectedFile_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected file.
        /// </summary>
        public static string Common_Components_MainToolbar_DeleteSelectedFile_Tooltip {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_DeleteSelectedFile_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPEN FILE.
        /// </summary>
        public static string Common_Components_MainToolbar_OpenFile_Text {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_OpenFile_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File....
        /// </summary>
        public static string Common_Components_MainToolbar_OpenFile_ToolTip {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_OpenFile_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REFRESH.
        /// </summary>
        public static string Common_Components_MainToolbar_RefreshLog_Text {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_RefreshLog_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Log.
        /// </summary>
        public static string Common_Components_MainToolbar_RefreshLog_Tooltip {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_RefreshLog_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPEN FOLDER.
        /// </summary>
        public static string Common_Components_MainToolbar_SelectFolder_Text {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_SelectFolder_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder....
        /// </summary>
        public static string Common_Components_MainToolbar_SelectFolder_Tooltip {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_SelectFolder_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string CultureName {
            get {
                return ResourceManager.GetString("CultureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter {0}.
        /// </summary>
        public static string FilteredGridManager_BuildDataGrid_FilterTextBox_Tooltip {
            get {
                return ResourceManager.GetString("FilteredGridManager_BuildDataGrid_FilterTextBox_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMM d, HH:mm:ss.fff.
        /// </summary>
        public static string GlobalHelper_DISPLAY_DATETIME_FORMAT {
            get {
                return ResourceManager.GetString("GlobalHelper_DISPLAY_DATETIME_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -{0} s.
        /// </summary>
        public static string GlobalHelper_getTimeDelta_Negative_Text {
            get {
                return ResourceManager.GetString("GlobalHelper_getTimeDelta_Negative_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0} s.
        /// </summary>
        public static string GlobalHelper_getTimeDelta_Positive_Text {
            get {
                return ResourceManager.GetString("GlobalHelper_getTimeDelta_Positive_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading Favorites file!
        ///[{0}]
        ///
        ///{1}.
        /// </summary>
        public static string GlobalHelper_ParseFolderFile_Error_Text {
            get {
                return ResourceManager.GetString("GlobalHelper_ParseFolderFile_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string GlobalHelper_ParseFolderFile_Error_Title {
            get {
                return ResourceManager.GetString("GlobalHelper_ParseFolderFile_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading log file!
        ///[{0}]
        ///
        ///{1}.
        /// </summary>
        public static string GlobalHelper_ParseLogFile_Error_Text {
            get {
                return ResourceManager.GetString("GlobalHelper_ParseLogFile_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string GlobalHelper_ParseLogFile_Error_Title {
            get {
                return ResourceManager.GetString("GlobalHelper_ParseLogFile_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving Favorites file!
        ///[{0}]
        ///
        ///{1}.
        /// </summary>
        public static string GlobalHelper_SaveFolderFile_Error_Text {
            get {
                return ResourceManager.GetString("GlobalHelper_SaveFolderFile_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string GlobalHelper_SaveFolderFile_Error_Title {
            get {
                return ResourceManager.GetString("GlobalHelper_SaveFolderFile_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Refresh.
        /// </summary>
        public static string MainWindow_AutoRefresh_Checkbox_Text {
            get {
                return ResourceManager.GetString("MainWindow_AutoRefresh_Checkbox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease Interval.
        /// </summary>
        public static string MainWindow_AutoRefresh_DecreaseInterval_Tooltip {
            get {
                return ResourceManager.GetString("MainWindow_AutoRefresh_DecreaseInterval_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase Interval.
        /// </summary>
        public static string MainWindow_AutoRefresh_IncreaseInterval_Tooltip {
            get {
                return ResourceManager.GetString("MainWindow_AutoRefresh_IncreaseInterval_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Interval.
        /// </summary>
        public static string MainWindow_AutoRefresh_RefreshInterval_Tooltip {
            get {
                return ResourceManager.GetString("MainWindow_AutoRefresh_RefreshInterval_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App:.
        /// </summary>
        public static string MainWindow_DetailsBox_Application_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_Application_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class:.
        /// </summary>
        public static string MainWindow_DetailsBox_Class_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_Class_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File:.
        /// </summary>
        public static string MainWindow_DetailsBox_File_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_File_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Name:.
        /// </summary>
        public static string MainWindow_DetailsBox_HostName_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_HostName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Id:.
        /// </summary>
        public static string MainWindow_DetailsBox_ItemId_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_ItemId_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level:.
        /// </summary>
        public static string MainWindow_DetailsBox_Level_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_Level_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line:.
        /// </summary>
        public static string MainWindow_DetailsBox_Line_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_Line_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logger:.
        /// </summary>
        public static string MainWindow_DetailsBox_Logger_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_Logger_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Name:.
        /// </summary>
        public static string MainWindow_DetailsBox_MachineName_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_MachineName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message:.
        /// </summary>
        public static string MainWindow_DetailsBox_Message_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_Message_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method:.
        /// </summary>
        public static string MainWindow_DetailsBox_Method_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_Method_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread:.
        /// </summary>
        public static string MainWindow_DetailsBox_Thread_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_Thread_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throwable:.
        /// </summary>
        public static string MainWindow_DetailsBox_Throwable_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_Throwable_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δ [time diff with previous log entry]:.
        /// </summary>
        public static string MainWindow_DetailsBox_TimeDiff_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_TimeDiff_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Stamp:.
        /// </summary>
        public static string MainWindow_DetailsBox_TimeStamp_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_TimeStamp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name:.
        /// </summary>
        public static string MainWindow_DetailsBox_UserName_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_UserName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete File.
        /// </summary>
        public static string MainWindow_FilesListBoxContextMenu_DeleteFile_Header {
            get {
                return ResourceManager.GetString("MainWindow_FilesListBoxContextMenu_DeleteFile_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Selected Folder.
        /// </summary>
        public static string MainWindow_FilesListBoxContextMenu_OpenSelectedFolder_Header {
            get {
                return ResourceManager.GetString("MainWindow_FilesListBoxContextMenu_OpenSelectedFolder_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh File List.
        /// </summary>
        public static string MainWindow_FilesListBoxContextMenu_RefreshFileList_Header {
            get {
                return ResourceManager.GetString("MainWindow_FilesListBoxContextMenu_RefreshFileList_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All Files.
        /// </summary>
        public static string MainWindow_FilesListBoxContextMenu_SelectAll_Header {
            get {
                return ResourceManager.GetString("MainWindow_FilesListBoxContextMenu_SelectAll_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All Files.
        /// </summary>
        public static string MainWindow_FilesListBoxContextMenu_SelectNone_Header {
            get {
                return ResourceManager.GetString("MainWindow_FilesListBoxContextMenu_SelectNone_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dddd, MMMM d, yyyy h:mm:ss.fff tt.
        /// </summary>
        public static string MainWindow_FullDateTimeFormatWithMilliseconds {
            get {
                return ResourceManager.GetString("MainWindow_FullDateTimeFormatWithMilliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select columns....
        /// </summary>
        public static string MainWindow_GridColumnHeaderContextMenu_SelectColumns {
            get {
                return ResourceManager.GetString("MainWindow_GridColumnHeaderContextMenu_SelectColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy To Clipboard.
        /// </summary>
        public static string MainWindow_GridContextMenu_CopyToClipboard {
            get {
                return ResourceManager.GetString("MainWindow_GridContextMenu_CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File To Merge.
        /// </summary>
        public static string MainWindow_MergeFile_Tooltip {
            get {
                return ResourceManager.GetString("MainWindow_MergeFile_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECTION.
        /// </summary>
        public static string MainWindow_SelectionGroupBox_Header {
            get {
                return ResourceManager.GetString("MainWindow_SelectionGroupBox_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filtered items count / full items count.
        /// </summary>
        public static string MainWindow_SelectionTooltip {
            get {
                return ResourceManager.GetString("MainWindow_SelectionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHOW/HIDE.
        /// </summary>
        public static string MainWindow_ShowHideGroupBox_Header {
            get {
                return ResourceManager.GetString("MainWindow_ShowHideGroupBox_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YALV! - Yet Another Log4Net Viewer.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} s.
        /// </summary>
        public static string MainWindowVM_AutoRefreshIntervalLocalized_Format {
            get {
                return ResourceManager.GetString("MainWindowVM_AutoRefreshIntervalLocalized_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreadable File!
        ///
        ///{0}.
        /// </summary>
        public static string MainWindowVM_bkLoaderCompleted_UnreadableFile_Text {
            get {
                return ResourceManager.GetString("MainWindowVM_bkLoaderCompleted_UnreadableFile_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string MainWindowVM_bkLoaderCompleted_UnreadableFile_Title {
            get {
                return ResourceManager.GetString("MainWindowVM_bkLoaderCompleted_UnreadableFile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete all checked files?.
        /// </summary>
        public static string MainWindowVM_commandDeleteExecute_DeleteCheckedFiles_ConfirmText {
            get {
                return ResourceManager.GetString("MainWindowVM_commandDeleteExecute_DeleteCheckedFiles_ConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string MainWindowVM_commandDeleteExecute_DeleteCheckedFiles_ConfirmTitle {
            get {
                return ResourceManager.GetString("MainWindowVM_commandDeleteExecute_DeleteCheckedFiles_ConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete all selected files?.
        /// </summary>
        public static string MainWindowVM_commandDeleteExecute_DeleteSelectedFile_ConfirmText {
            get {
                return ResourceManager.GetString("MainWindowVM_commandDeleteExecute_DeleteSelectedFile_ConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string MainWindowVM_commandDeleteExecute_DeleteSelectedFile_ConfirmTitle {
            get {
                return ResourceManager.GetString("MainWindowVM_commandDeleteExecute_DeleteSelectedFile_ConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Log File.
        /// </summary>
        public static string MainWindowVM_commandOpenFileExecute_Add_Log_File {
            get {
                return ResourceManager.GetString("MainWindowVM_commandOpenFileExecute_Add_Log_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string MainWindowVM_commandOpenFileExecute_AllFilesCaption {
            get {
                return ResourceManager.GetString("MainWindowVM_commandOpenFileExecute_AllFilesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Log File.
        /// </summary>
        public static string MainWindowVM_commandOpenFileExecute_Open_Log_File {
            get {
                return ResourceManager.GetString("MainWindowVM_commandOpenFileExecute_Open_Log_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml files.
        /// </summary>
        public static string MainWindowVM_commandOpenFileExecute_XmlFilesCaption {
            get {
                return ResourceManager.GetString("MainWindowVM_commandOpenFileExecute_XmlFilesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Log Folder.
        /// </summary>
        public static string MainWindowVM_commandSelectFolderExecute_Description {
            get {
                return ResourceManager.GetString("MainWindowVM_commandSelectFolderExecute_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting file!
        ///[{0}]
        ///
        ///{1}.
        /// </summary>
        public static string MainWindowVM_deleteFile_ErrorMessage_Text {
            get {
                return ResourceManager.GetString("MainWindowVM_deleteFile_ErrorMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MainWindowVM_deleteFile_ErrorMessage_Title {
            get {
                return ResourceManager.GetString("MainWindowVM_deleteFile_ErrorMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App.
        /// </summary>
        public static string MainWindowVM_InitDataGrid_AppColumn_Header {
            get {
                return ResourceManager.GetString("MainWindowVM_InitDataGrid_AppColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string MainWindowVM_InitDataGrid_ClassColumn_Header {
            get {
                return ResourceManager.GetString("MainWindowVM_InitDataGrid_ClassColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HostName.
        /// </summary>
        public static string MainWindowVM_InitDataGrid_HostNameColumn_Header {
            get {
                return ResourceManager.GetString("MainWindowVM_InitDataGrid_HostNameColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string MainWindowVM_InitDataGrid_IdColumn_Header {
            get {
                return ResourceManager.GetString("MainWindowVM_InitDataGrid_IdColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string MainWindowVM_InitDataGrid_LevelColumn_Header {
            get {
                return ResourceManager.GetString("MainWindowVM_InitDataGrid_LevelColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logger.
        /// </summary>
        public static string MainWindowVM_InitDataGrid_LoggerColumn_Header {
            get {
                return ResourceManager.GetString("MainWindowVM_InitDataGrid_LoggerColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Name.
        /// </summary>
        public static string MainWindowVM_InitDataGrid_MachineNameColumn_Header {
            get {
                return ResourceManager.GetString("MainWindowVM_InitDataGrid_MachineNameColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string MainWindowVM_InitDataGrid_MessageColumn_Header {
            get {
                return ResourceManager.GetString("MainWindowVM_InitDataGrid_MessageColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        public static string MainWindowVM_InitDataGrid_MethodColumn_Header {
            get {
                return ResourceManager.GetString("MainWindowVM_InitDataGrid_MethodColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread.
        /// </summary>
        public static string MainWindowVM_InitDataGrid_ThreadColumn_Header {
            get {
                return ResourceManager.GetString("MainWindowVM_InitDataGrid_ThreadColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        public static string MainWindowVM_InitDataGrid_TimeStampColumn_Header {
            get {
                return ResourceManager.GetString("MainWindowVM_InitDataGrid_TimeStampColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string MainWindowVM_InitDataGrid_UserNameColumn_Header {
            get {
                return ResourceManager.GetString("MainWindowVM_InitDataGrid_UserNameColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory not found!
        ///[{0}].
        /// </summary>
        public static string MainWindowVM_loadFolderFiles_ErrorMessage_Text {
            get {
                return ResourceManager.GetString("MainWindowVM_loadFolderFiles_ErrorMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MainWindowVM_loadFolderFiles_ErrorMessageText_Title {
            get {
                return ResourceManager.GetString("MainWindowVM_loadFolderFiles_ErrorMessageText_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        public static string MainWindowVM_updateJumpList_CustomCategoryName {
            get {
                return ResourceManager.GetString("MainWindowVM_updateJumpList_CustomCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YALV! - Edit Favorites.
        /// </summary>
        public static string SaveFolderPath_Title {
            get {
                return ResourceManager.GetString("SaveFolderPath_Title", resourceCulture);
            }
        }
    }
}
