//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18033
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YALV.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YALV.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        public static string About_AboutGroupBox_Header {
            get {
                return ResourceManager.GetString("About_AboutGroupBox_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Credits.
        /// </summary>
        public static string About_CreditsGroupBox_Header {
            get {
                return ResourceManager.GetString("About_CreditsGroupBox_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на YALV! is a log viewer for Log4Net that allow to compare multiple logs file simultaneously.
        ///
        ///MAIN FEATURES:
        ///- Log files merging
        ///- Dynamic filtering
        ///- Dynamic show/hide log levels
        ///- Save favorite log folders
        ///- Open most recently used files
        ///- Column sorting
        ///
        ///Log4Net config file must be setup with XmlLayoutSchemaLog4j layout; just need a few lines in your application config file to configure it to use this format (see examples on right).
        ///
        ///It is a WPF Application based on .NET Framework 4.0 and writt [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string About_Description {
            get {
                return ResourceManager.GetString("About_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на YALV! - Yet Another Log4Net Viewer.
        /// </summary>
        public static string About_Header_Text {
            get {
                return ResourceManager.GetString("About_Header_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log4Net Configuration.
        /// </summary>
        public static string About_Log4NetConfigurationGroupbox_Header {
            get {
                return ResourceManager.GetString("About_Log4NetConfigurationGroupbox_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sample 1:.
        /// </summary>
        public static string About_Log4NetConfigurationGroupbox_Sample1_Title {
            get {
                return ResourceManager.GetString("About_Log4NetConfigurationGroupbox_Sample1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sample 2:.
        /// </summary>
        public static string About_Log4NetConfigurationGroupbox_Sample2_Title {
            get {
                return ResourceManager.GetString("About_Log4NetConfigurationGroupbox_Sample2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на YALV! - About.
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version {0}.
        /// </summary>
        public static string About_Version_Text {
            get {
                return ResourceManager.GetString("About_Version_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string AddFolderPath_Grid_NameColumn_Name {
            get {
                return ResourceManager.GetString("AddFolderPath_Grid_NameColumn_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Path.
        /// </summary>
        public static string AddFolderPath_Grid_PathColumn_Name {
            get {
                return ResourceManager.GetString("AddFolderPath_Grid_PathColumn_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Folders list saved!.
        /// </summary>
        public static string AddFolderPathVM_commandSaveExecute_SuccessMessage {
            get {
                return ResourceManager.GetString("AddFolderPathVM_commandSaveExecute_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Success.
        /// </summary>
        public static string AddFolderPathVM_commandSaveExecute_SuccessTitle {
            get {
                return ResourceManager.GetString("AddFolderPathVM_commandSaveExecute_SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading....
        /// </summary>
        public static string CircularProgressBar_CircularProgressBar_BusyText {
            get {
                return ResourceManager.GetString("CircularProgressBar_CircularProgressBar_BusyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add folder to Favorites.
        /// </summary>
        public static string Common_Components_AddRemoveMenu_FileMenu_AddNewItem_Header {
            get {
                return ResourceManager.GetString("Common_Components_AddRemoveMenu_FileMenu_AddNewItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        public static string Common_Components_AddRemoveMenu_FileMenu_Exit_Header {
            get {
                return ResourceManager.GetString("Common_Components_AddRemoveMenu_FileMenu_Exit_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File.
        /// </summary>
        public static string Common_Components_AddRemoveMenu_FileMenu_Header {
            get {
                return ResourceManager.GetString("Common_Components_AddRemoveMenu_FileMenu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove folder from Favorites.
        /// </summary>
        public static string Common_Components_AddRemoveMenu_FileMenu_RemoveSelectedItem_Header {
            get {
                return ResourceManager.GetString("Common_Components_AddRemoveMenu_FileMenu_RemoveSelectedItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save Favorites.
        /// </summary>
        public static string Common_Components_AddRemoveMenu_FileMenu_SaveList_Header {
            get {
                return ResourceManager.GetString("Common_Components_AddRemoveMenu_FileMenu_SaveList_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ADD.
        /// </summary>
        public static string Common_Components_AddRemoveToolbar_AddNewItem_Text {
            get {
                return ResourceManager.GetString("Common_Components_AddRemoveToolbar_AddNewItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Folder to Favorites.
        /// </summary>
        public static string Common_Components_AddRemoveToolbar_AddNewItem_Tooltip {
            get {
                return ResourceManager.GetString("Common_Components_AddRemoveToolbar_AddNewItem_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на REMOVE.
        /// </summary>
        public static string Common_Components_AddRemoveToolbar_RemoveSelectedItem_Text {
            get {
                return ResourceManager.GetString("Common_Components_AddRemoveToolbar_RemoveSelectedItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove Selected Folder from Favorites.
        /// </summary>
        public static string Common_Components_AddRemoveToolbar_RemoveSelectedItem_Tooltip {
            get {
                return ResourceManager.GetString("Common_Components_AddRemoveToolbar_RemoveSelectedItem_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SAVE.
        /// </summary>
        public static string Common_Components_AddRemoveToolbar_SaveList_Text {
            get {
                return ResourceManager.GetString("Common_Components_AddRemoveToolbar_SaveList_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save Favorites.
        /// </summary>
        public static string Common_Components_AddRemoveToolbar_SaveList_Tooltip {
            get {
                return ResourceManager.GetString("Common_Components_AddRemoveToolbar_SaveList_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        public static string Common_Components_MainMenu_AboutMenu_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_AboutMenu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add File....
        /// </summary>
        public static string Common_Components_MainMenu_FileMenu_AddFile_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_FileMenu_AddFile_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Folder to Favorites....
        /// </summary>
        public static string Common_Components_MainMenu_FileMenu_AddFolderPath_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_FileMenu_AddFolderPath_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        public static string Common_Components_MainMenu_FileMenu_Exit_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_FileMenu_Exit_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File.
        /// </summary>
        public static string Common_Components_MainMenu_FileMenu_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_FileMenu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open File....
        /// </summary>
        public static string Common_Components_MainMenu_FileMenu_OpenFile_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_FileMenu_OpenFile_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recent Files.
        /// </summary>
        public static string Common_Components_MainMenu_FileMenu_RecentFiles_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_FileMenu_RecentFiles_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open Folder....
        /// </summary>
        public static string Common_Components_MainMenu_FileMenu_SelectFolder_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_FileMenu_SelectFolder_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear Filters.
        /// </summary>
        public static string Common_Components_MainMenu_ViewMenu_ClearFilters_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_ViewMenu_ClearFilters_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete File.
        /// </summary>
        public static string Common_Components_MainMenu_ViewMenu_DeleteFile_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_ViewMenu_DeleteFile_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на View.
        /// </summary>
        public static string Common_Components_MainMenu_ViewMenu_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_ViewMenu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open containing Folder in Explorer.
        /// </summary>
        public static string Common_Components_MainMenu_ViewMenu_OpenSelectedFolder_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_ViewMenu_OpenSelectedFolder_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refresh File List.
        /// </summary>
        public static string Common_Components_MainMenu_ViewMenu_RefreshFileList_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_ViewMenu_RefreshFileList_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refresh Log.
        /// </summary>
        public static string Common_Components_MainMenu_ViewMenu_RefreshLog_Header {
            get {
                return ResourceManager.GetString("Common_Components_MainMenu_ViewMenu_RefreshLog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ADD FILE.
        /// </summary>
        public static string Common_Components_MainToolbar_AddFile_Text {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_AddFile_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add File....
        /// </summary>
        public static string Common_Components_MainToolbar_AddFile_Tooltip {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_AddFile_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ADD FOLDER.
        /// </summary>
        public static string Common_Components_MainToolbar_AddFolderPath_Text {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_AddFolderPath_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Folder to Favorites....
        /// </summary>
        public static string Common_Components_MainToolbar_AddFolderPath_Tooltip {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_AddFolderPath_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CLEAR FILTERS.
        /// </summary>
        public static string Common_Components_MainToolbar_ClearFilters_Text {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_ClearFilters_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear Filters.
        /// </summary>
        public static string Common_Components_MainToolbar_ClearFilters_Tooltip {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_ClearFilters_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DELETE FILE.
        /// </summary>
        public static string Common_Components_MainToolbar_DeleteSelectedFile_Text {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_DeleteSelectedFile_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete selected file.
        /// </summary>
        public static string Common_Components_MainToolbar_DeleteSelectedFile_Tooltip {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_DeleteSelectedFile_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OPEN FILE.
        /// </summary>
        public static string Common_Components_MainToolbar_OpenFile_Text {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_OpenFile_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open File....
        /// </summary>
        public static string Common_Components_MainToolbar_OpenFile_ToolTip {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_OpenFile_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на REFRESH.
        /// </summary>
        public static string Common_Components_MainToolbar_RefreshLog_Text {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_RefreshLog_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refresh Log.
        /// </summary>
        public static string Common_Components_MainToolbar_RefreshLog_Tooltip {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_RefreshLog_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OPEN FOLDER.
        /// </summary>
        public static string Common_Components_MainToolbar_SelectFolder_Text {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_SelectFolder_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open Folder....
        /// </summary>
        public static string Common_Components_MainToolbar_SelectFolder_Tooltip {
            get {
                return ResourceManager.GetString("Common_Components_MainToolbar_SelectFolder_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на en.
        /// </summary>
        public static string CultureName {
            get {
                return ResourceManager.GetString("CultureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filter {0}.
        /// </summary>
        public static string FilteredGridManager_BuildDataGrid_FilterTextBox_Tooltip {
            get {
                return ResourceManager.GetString("FilteredGridManager_BuildDataGrid_FilterTextBox_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MMM d, HH:mm:ss.fff.
        /// </summary>
        public static string GlobalHelper_DISPLAY_DATETIME_FORMAT {
            get {
                return ResourceManager.GetString("GlobalHelper_DISPLAY_DATETIME_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на -{0} s.
        /// </summary>
        public static string GlobalHelper_getTimeDelta_Negative_Text {
            get {
                return ResourceManager.GetString("GlobalHelper_getTimeDelta_Negative_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на +{0} s.
        /// </summary>
        public static string GlobalHelper_getTimeDelta_Positive_Text {
            get {
                return ResourceManager.GetString("GlobalHelper_getTimeDelta_Positive_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error reading Favorites file!
        ///[{0}]
        ///
        ///{1}.
        /// </summary>
        public static string GlobalHelper_ParseFolderFile_Error_Text {
            get {
                return ResourceManager.GetString("GlobalHelper_ParseFolderFile_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string GlobalHelper_ParseFolderFile_Error_Title {
            get {
                return ResourceManager.GetString("GlobalHelper_ParseFolderFile_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error reading log file!
        ///[{0}]
        ///
        ///{1}.
        /// </summary>
        public static string GlobalHelper_ParseLogFile_Error_Text {
            get {
                return ResourceManager.GetString("GlobalHelper_ParseLogFile_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string GlobalHelper_ParseLogFile_Error_Title {
            get {
                return ResourceManager.GetString("GlobalHelper_ParseLogFile_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error saving Favorites file!
        ///[{0}]
        ///
        ///{1}.
        /// </summary>
        public static string GlobalHelper_SaveFolderFile_Error_Text {
            get {
                return ResourceManager.GetString("GlobalHelper_SaveFolderFile_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string GlobalHelper_SaveFolderFile_Error_Title {
            get {
                return ResourceManager.GetString("GlobalHelper_SaveFolderFile_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto Refresh.
        /// </summary>
        public static string MainWindow_AutoRefresh_Checkbox_Text {
            get {
                return ResourceManager.GetString("MainWindow_AutoRefresh_Checkbox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Decrease Interval.
        /// </summary>
        public static string MainWindow_AutoRefresh_DecreaseInterval_Tooltip {
            get {
                return ResourceManager.GetString("MainWindow_AutoRefresh_DecreaseInterval_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Increase Interval.
        /// </summary>
        public static string MainWindow_AutoRefresh_IncreaseInterval_Tooltip {
            get {
                return ResourceManager.GetString("MainWindow_AutoRefresh_IncreaseInterval_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refresh Interval.
        /// </summary>
        public static string MainWindow_AutoRefresh_RefreshInterval_Tooltip {
            get {
                return ResourceManager.GetString("MainWindow_AutoRefresh_RefreshInterval_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на App:.
        /// </summary>
        public static string MainWindow_DetailsBox_Application_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_Application_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Class:.
        /// </summary>
        public static string MainWindow_DetailsBox_Class_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_Class_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File:.
        /// </summary>
        public static string MainWindow_DetailsBox_File_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_File_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Host Name:.
        /// </summary>
        public static string MainWindow_DetailsBox_HostName_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_HostName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Item Id:.
        /// </summary>
        public static string MainWindow_DetailsBox_ItemId_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_ItemId_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Level:.
        /// </summary>
        public static string MainWindow_DetailsBox_Level_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_Level_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Line:.
        /// </summary>
        public static string MainWindow_DetailsBox_Line_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_Line_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Logger:.
        /// </summary>
        public static string MainWindow_DetailsBox_Logger_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_Logger_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Machine Name:.
        /// </summary>
        public static string MainWindow_DetailsBox_MachineName_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_MachineName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Message:.
        /// </summary>
        public static string MainWindow_DetailsBox_Message_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_Message_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Method:.
        /// </summary>
        public static string MainWindow_DetailsBox_Method_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_Method_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Thread:.
        /// </summary>
        public static string MainWindow_DetailsBox_Thread_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_Thread_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Throwable:.
        /// </summary>
        public static string MainWindow_DetailsBox_Throwable_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_Throwable_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Δ [time diff with previous log entry]:.
        /// </summary>
        public static string MainWindow_DetailsBox_TimeDiff_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_TimeDiff_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time Stamp:.
        /// </summary>
        public static string MainWindow_DetailsBox_TimeStamp_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_TimeStamp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User Name:.
        /// </summary>
        public static string MainWindow_DetailsBox_UserName_Text {
            get {
                return ResourceManager.GetString("MainWindow_DetailsBox_UserName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete File.
        /// </summary>
        public static string MainWindow_FilesListBoxContextMenu_DeleteFile_Header {
            get {
                return ResourceManager.GetString("MainWindow_FilesListBoxContextMenu_DeleteFile_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open Selected Folder.
        /// </summary>
        public static string MainWindow_FilesListBoxContextMenu_OpenSelectedFolder_Header {
            get {
                return ResourceManager.GetString("MainWindow_FilesListBoxContextMenu_OpenSelectedFolder_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refresh File List.
        /// </summary>
        public static string MainWindow_FilesListBoxContextMenu_RefreshFileList_Header {
            get {
                return ResourceManager.GetString("MainWindow_FilesListBoxContextMenu_RefreshFileList_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на dddd, MMMM d, yyyy h:mm:ss.fff tt.
        /// </summary>
        public static string MainWindow_FullDateTimeFormatWithMilliseconds {
            get {
                return ResourceManager.GetString("MainWindow_FullDateTimeFormatWithMilliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy To Clipboard.
        /// </summary>
        public static string MainWindow_GridContextMenu_CopyToClipboard {
            get {
                return ResourceManager.GetString("MainWindow_GridContextMenu_CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select File To Merge.
        /// </summary>
        public static string MainWindow_MergeFile_Tooltip {
            get {
                return ResourceManager.GetString("MainWindow_MergeFile_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECTION.
        /// </summary>
        public static string MainWindow_SelectionGroupBox_Header {
            get {
                return ResourceManager.GetString("MainWindow_SelectionGroupBox_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на filtered items count / full items count.
        /// </summary>
        public static string MainWindow_SelectionTooltip {
            get {
                return ResourceManager.GetString("MainWindow_SelectionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SHOW/HIDE.
        /// </summary>
        public static string MainWindow_ShowHideGroupBox_Header {
            get {
                return ResourceManager.GetString("MainWindow_ShowHideGroupBox_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на YALV! - Yet Another Log4Net Viewer.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} s.
        /// </summary>
        public static string MainWindowVM_AutoRefreshIntervalLocalized_Format {
            get {
                return ResourceManager.GetString("MainWindowVM_AutoRefreshIntervalLocalized_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unreadable File!
        ///
        ///{0}.
        /// </summary>
        public static string MainWindowVM_bkLoaderCompleted_UnreadableFile_Text {
            get {
                return ResourceManager.GetString("MainWindowVM_bkLoaderCompleted_UnreadableFile_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning.
        /// </summary>
        public static string MainWindowVM_bkLoaderCompleted_UnreadableFile_Title {
            get {
                return ResourceManager.GetString("MainWindowVM_bkLoaderCompleted_UnreadableFile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to delete all checked files?.
        /// </summary>
        public static string MainWindowVM_commandDeleteExecute_DeleteCheckedFiles_ConfirmText {
            get {
                return ResourceManager.GetString("MainWindowVM_commandDeleteExecute_DeleteCheckedFiles_ConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm Delete.
        /// </summary>
        public static string MainWindowVM_commandDeleteExecute_DeleteCheckedFiles_ConfirmTitle {
            get {
                return ResourceManager.GetString("MainWindowVM_commandDeleteExecute_DeleteCheckedFiles_ConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to delete all selected files?.
        /// </summary>
        public static string MainWindowVM_commandDeleteExecute_DeleteSelectedFile_ConfirmText {
            get {
                return ResourceManager.GetString("MainWindowVM_commandDeleteExecute_DeleteSelectedFile_ConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm Delete.
        /// </summary>
        public static string MainWindowVM_commandDeleteExecute_DeleteSelectedFile_ConfirmTitle {
            get {
                return ResourceManager.GetString("MainWindowVM_commandDeleteExecute_DeleteSelectedFile_ConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Log File.
        /// </summary>
        public static string MainWindowVM_commandOpenFileExecute_Add_Log_File {
            get {
                return ResourceManager.GetString("MainWindowVM_commandOpenFileExecute_Add_Log_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All files.
        /// </summary>
        public static string MainWindowVM_commandOpenFileExecute_AllFilesCaption {
            get {
                return ResourceManager.GetString("MainWindowVM_commandOpenFileExecute_AllFilesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open Log File.
        /// </summary>
        public static string MainWindowVM_commandOpenFileExecute_Open_Log_File {
            get {
                return ResourceManager.GetString("MainWindowVM_commandOpenFileExecute_Open_Log_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Xml files.
        /// </summary>
        public static string MainWindowVM_commandOpenFileExecute_XmlFilesCaption {
            get {
                return ResourceManager.GetString("MainWindowVM_commandOpenFileExecute_XmlFilesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Log Folder.
        /// </summary>
        public static string MainWindowVM_commandSelectFolderExecute_Description {
            get {
                return ResourceManager.GetString("MainWindowVM_commandSelectFolderExecute_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error deleting file!
        ///[{0}]
        ///
        ///{1}.
        /// </summary>
        public static string MainWindowVM_deleteFile_ErrorMessage_Text {
            get {
                return ResourceManager.GetString("MainWindowVM_deleteFile_ErrorMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string MainWindowVM_deleteFile_ErrorMessage_Title {
            get {
                return ResourceManager.GetString("MainWindowVM_deleteFile_ErrorMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на App.
        /// </summary>
        public static string MainWindowVM_InitDataGrid_AppColumn_Header {
            get {
                return ResourceManager.GetString("MainWindowVM_InitDataGrid_AppColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Class.
        /// </summary>
        public static string MainWindowVM_InitDataGrid_ClassColumn_Header {
            get {
                return ResourceManager.GetString("MainWindowVM_InitDataGrid_ClassColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на HostName.
        /// </summary>
        public static string MainWindowVM_InitDataGrid_HostNameColumn_Header {
            get {
                return ResourceManager.GetString("MainWindowVM_InitDataGrid_HostNameColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Id.
        /// </summary>
        public static string MainWindowVM_InitDataGrid_IdColumn_Header {
            get {
                return ResourceManager.GetString("MainWindowVM_InitDataGrid_IdColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Level.
        /// </summary>
        public static string MainWindowVM_InitDataGrid_LevelColumn_Header {
            get {
                return ResourceManager.GetString("MainWindowVM_InitDataGrid_LevelColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Logger.
        /// </summary>
        public static string MainWindowVM_InitDataGrid_LoggerColumn_Header {
            get {
                return ResourceManager.GetString("MainWindowVM_InitDataGrid_LoggerColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Machine Name.
        /// </summary>
        public static string MainWindowVM_InitDataGrid_MachineNameColumn_Header {
            get {
                return ResourceManager.GetString("MainWindowVM_InitDataGrid_MachineNameColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Message.
        /// </summary>
        public static string MainWindowVM_InitDataGrid_MessageColumn_Header {
            get {
                return ResourceManager.GetString("MainWindowVM_InitDataGrid_MessageColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Method.
        /// </summary>
        public static string MainWindowVM_InitDataGrid_MethodColumn_Header {
            get {
                return ResourceManager.GetString("MainWindowVM_InitDataGrid_MethodColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Thread.
        /// </summary>
        public static string MainWindowVM_InitDataGrid_ThreadColumn_Header {
            get {
                return ResourceManager.GetString("MainWindowVM_InitDataGrid_ThreadColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Timestamp.
        /// </summary>
        public static string MainWindowVM_InitDataGrid_TimeStampColumn_Header {
            get {
                return ResourceManager.GetString("MainWindowVM_InitDataGrid_TimeStampColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User Name.
        /// </summary>
        public static string MainWindowVM_InitDataGrid_UserNameColumn_Header {
            get {
                return ResourceManager.GetString("MainWindowVM_InitDataGrid_UserNameColumn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Directory not found!
        ///[{0}].
        /// </summary>
        public static string MainWindowVM_loadFolderFiles_ErrorMessage_Text {
            get {
                return ResourceManager.GetString("MainWindowVM_loadFolderFiles_ErrorMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string MainWindowVM_loadFolderFiles_ErrorMessageText_Title {
            get {
                return ResourceManager.GetString("MainWindowVM_loadFolderFiles_ErrorMessageText_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recent.
        /// </summary>
        public static string MainWindowVM_updateJumpList_CustomCategoryName {
            get {
                return ResourceManager.GetString("MainWindowVM_updateJumpList_CustomCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на YALV! - Edit Favorites.
        /// </summary>
        public static string SaveFolderPath_Title {
            get {
                return ResourceManager.GetString("SaveFolderPath_Title", resourceCulture);
            }
        }
    }
}
